## Normalization and acuuracy
### Kalyani Khandait

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
#from google.colab import drive
#drive.mount('/contents/drive')

Mounted at /content/drive

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/shivang98/Social-Network-ads-Boost/master/Social_Network_Ads.csv')

In [ ]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df.tail()

      User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [ ]:
df.shape

(168, 757)

In [ ]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [ ]:
df.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [ ]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
corr=df.corr()
print(corr.shape)

(4, 4)

Start

In [ ]:
x=df.drop(["Gender",'Purchased'],axis=1)
y=df['Purchased']
x.head()

    User ID  Age  EstimatedSalary
0  15624510   19            19000
1  15810944   35            20000
2  15668575   26            43000
3  15603246   27            57000
4  15804002   19            76000

In [ ]:
# Split into train & test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=50)
print("Success")

Success

In [ ]:
# Build The Model
from sklearn.linear_model import LogisticRegression
basemodel=LogisticRegression()
basemodel.fit(x_train,y_train)
print("Training accuracy",basemodel.score(x_train,y_train)*100)

Training accuracy 63.4375

In [ ]:
# Make Predictions On Test Data
y_predict=basemodel.predict(x_test)
print("Test accuracy:",basemodel.score(x_test,y_test)*100)

Test accuracy: 67.5

Normalize (max min)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scalar= MinMaxScaler()
x=df[['Age','EstimatedSalary']]
x_scaled=scalar.fit_transform(x)
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2,random_state=42)
print("Succesesfull Split")

Succesesfull Split

In [ ]:
model=LogisticRegression()
model.fit(x_train,y_train)
y_predict=model.predict(x_test)
print('Training Accuracy',model.score(x_train,y_train)*100)
print('Testing Accuracy',model.score(x_test,y_test)*100)

Training Accuracy 80.9375
Training Accuracy 87.5

MEasure the Accuracy

In [ ]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_predict)
print(acc)

0.875

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict)
print(cm)

[[51  1]
 [ 9 19]]